"""Deterministic 640x360 four-bit board UI assets; run in the project .venv.

Noto Sans CJK (SIL OFL) supplies rasterized fixed labels, DejaVu Sans Mono
(Bitstream Vera license) supplies the small ASCII bitmap. No font files are
distributed. Generated assets are committed so builds need neither font nor PIL.
"""
from pathlib import Path
import math
import os
import numpy as np
from PIL import Image, ImageDraw, ImageFont

ROOT=Path(__file__).resolve().parents[1]
PALETTE=['0b151d','101f29','29434f','718f9e','b0c8d3','e4f0f3',
         '143e37','1d6754','2e9c78','54efbb','193954','71c8ff','f2c879','e77878','987bd3','ffffff']
FONT=os.environ.get('MIC_CJK_FONT','/usr/share/fonts/noto-cjk/NotoSansCJK-Regular.ttc')
MONO=os.environ.get('MIC_MONO_FONT','/usr/share/fonts/TTF/DejaVuSansMono.ttf')

def project(az,el):
    a=math.radians(az+25);e=math.radians(el)
    return (236+158*math.cos(e)*math.cos(a),213-158*(math.cos(e)*math.sin(a)*.36+math.sin(e)*.95))

def generate():
    image=Image.new('P',(640,360),0)
    image.putpalette([int(c[i:i+2],16) for c in PALETTE for i in (0,2,4)]+[0]*(768-48))
    d=ImageDraw.Draw(image)
    def text(x,y,s,size=10,color=4):d.text((x,y),s,font=ImageFont.truetype(FONT,size),fill=color)
    d.rectangle((480,42,639,343),fill=1);d.rectangle((0,286,479,343),fill=1)
    d.line((0,41,639,41),fill=2);d.line((480,42,480,343),fill=2);d.line((0,343,639,343),fill=2)
    text(20,8,'声源方向雷达',19,5);text(183,19,'AX7020  /  7-MIC ARRAY',9,3)
    text(20,49,'上半空间 · DIRECTION',10,4)
    for e in (0,30,60):d.line([project(a,e) for a in range(361)],fill=2,width=1)
    for a in range(0,360,30):d.line([project(a,e) for e in range(91)],fill=2,width=1)
    text(209,44,'90° 正上方',9,4)
    for m in range(6):
        x,y=project(-60*m,0);d.ellipse((x-2,y-2,x+2,y+2),fill=3)
        dx,dy=x-236,y-213
        text(x+dx*.08-8,y+dy*.13-7,f'M{m}',9,4)
        sx,sy=236+dx*.13,213+dy*.13;d.ellipse((sx-2,sy-2,sx+2,sy+2),fill=4)
    d.ellipse((233,210,239,216),fill=4)
    text(499,51,'方位角 / AZIMUTH',10);text(499,118,'俯仰角 / ELEVATION',10)
    text(499,190,'接收强度 / RELATIVE',10)
    text(500,260,'灯环同步 · M0 ↑',9,3)
    text(21,290,'M6 实时频谱',10);text(369,290,'固定 dBFS 刻度',8,3)
    text(24,329,'0',8,3);text(206,329,'4 kHz',8,3);text(392,329,'8.1 kHz',8,3)
    text(20,347,'单声源  |  M0 = 0°，逆时针为正  |  球面半径不表示距离',8,3)
    text(502,347,'720p60  /  PL VIDEO',8,3)
    p=np.array(image,dtype=np.uint8).ravel()
    packed=(p[::2]|(p[1::2]<<4)).tobytes()
    runs=[];last=packed[0];n=0
    for b in packed:
        if b!=last or n==65535:runs.append((n<<8)|last);last=b;n=0
        n+=1
    runs.append((n<<8)|last)
    glyph=[];font=ImageFont.truetype(MONO,12)
    for c in range(32,128):
        g=Image.new('1',(8,14));ImageDraw.Draw(g).text((0,-1),chr(c),font=font,fill=1)
        glyph.extend(sum((1<<x) for x in range(8) if g.getpixel((x,y))) for y in range(14))
    out=ROOT/'sw/mic_demo/radar_assets.h'
    with out.open('w') as f:
        f.write('/* Generated by tools/make_radar_assets.py. Noto CJK / DejaVu glyphs.\n'
                ' * Font licenses and attribution: see THIRD_PARTY_NOTICES.md. */\n')
        f.write('#ifndef RADAR_ASSETS_H\n#define RADAR_ASSETS_H\n#include <stdint.h>\n')
        f.write('static const uint32_t radar_background_rle[]={\n')
        for i in range(0,len(runs),10):f.write(','.join(f'0x{x:06x}' for x in runs[i:i+10])+',\n')
        f.write('};\nstatic const uint8_t radar_glyphs[96][14]={\n')
        for i in range(96):f.write('{'+','.join(str(x) for x in glyph[i*14:(i+1)*14])+'},\n')
        f.write('};\n#endif\n')
    (ROOT/'outputs/hdmi').mkdir(parents=True,exist_ok=True)
    image.convert('RGB').resize((1280,720),Image.Resampling.NEAREST).save(ROOT/'outputs/hdmi/background.png')
    print(f'Background {len(packed)} bytes -> {len(runs)*4} RLE bytes; generated {out}')

if __name__=='__main__':generate()
